# -*- coding: utf-8 -*-
"""Similarity Percentage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHAibK_0wIM1AoBo-JAg5lCaQpim1kff
"""

import numpy as np

# Assuming you have the angular distance value
angular_distance = 1.5671502

# Convert angular distance to cosine similarity
cosine_similarity = (np.cos(angular_distance) + 1) / 2

# Calculate similarity percentage
similarity_percentage = cosine_similarity * 100

# Print the similarity percentage
print("Similarity Percentage: {:.2f}%".format(similarity_percentage))